name: Run tests

on: 
  push:
    branches: [ feature*, master, develop ]
    paths-ignore:
      - 'README.md'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup system package
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.1-cli'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      
      - name: Run composer install
        run: |
          composer install -n --prefer-dist
          npm install --save-dev vue @vitejs/plugin-vue
          npm run build
      
      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
 
      - name: Run tests
        run: php artisan test

  eslint:
    name: Run fix eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.10.0'

      - name: Install dependencies
        run: npm install --save-dev eslint eslint-plugin-vue

      - name: Fix ESLint issues
        run: npm run fix:eslint
